// ============================================================================
// DnD Offline Multiplayer - LLM Client (LM Studio)
// ============================================================================

/**
 * Interface for NPC generated by AI
 */
interface GeneratedNPC {
  name: string;
  description?: string;
  role: 'friendly' | 'neutral' | 'hostile';
}

/**
 * Interface for Event generated by AI
 */
interface GeneratedEvent {
  title: string;
  description?: string;
  difficulty?: string;
}

/**
 * LM Studio Client - AI-powered content generation
 */
export class LLMClient {
  private baseUrl: string;
  private apiToken: string | null;
  private model: string;

  constructor() {
    this.baseUrl = localStorage.getItem('lmStudioUrl') || 'http://localhost:1234/v1/chat/completions';
    this.apiToken = localStorage.getItem('lmStudioToken') || null;
    this.model = localStorage.getItem('lmStudioModel') || 'local-model';
  }

  setBaseUrl(url: string): void {
    this.baseUrl = url;
    localStorage.setItem('lmStudioUrl', url);
  }

  getBaseUrl(): string {
    return this.baseUrl;
  }

  setApiToken(token: string): void {
    this.apiToken = token || null;
    if (token) {
      localStorage.setItem('lmStudioToken', token);
    } else {
      localStorage.removeItem('lmStudioToken');
    }
  }

  getApiToken(): string | null {
    return this.apiToken;
  }

  setModel(model: string): void {
    this.model = model;
    localStorage.setItem('lmStudioModel', model);
  }

  getModel(): string {
    return this.model;
  }

  private getHeaders(): Record<string, string> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    
    if (this.apiToken) {
      headers['Authorization'] = `Bearer ${this.apiToken}`;
    }
    
    return headers;
  }

  private async fetchModels(): Promise<string[]> {
    try {
      // LM Studio provides /v1/models endpoint to list available models
      const baseUrlWithoutEndpoint = this.baseUrl.replace('/v1/chat/completions', '');
      const response = await fetch(`${baseUrlWithoutEndpoint}/v1/models`, {
        method: 'GET',
        headers: this.getHeaders(),
      });

      if (response.ok) {
        const data = await response.json();
        return data.data?.map((m: any) => m.id) || ['local-model'];
      }
    } catch (error) {
      console.warn('Failed to fetch models:', error);
    }
    return ['local-model']; // Fallback
  }

  async generateScene(prompt: string, context: Record<string, unknown> = {}): Promise<string> {
    try {
      const messages = [
        {
          role: 'system' as const,
          content: `You are a D&D Dungeon Master assistant. Help create engaging scenes, NPCs, and events. 
                   Format your responses in markdown for better readability. Keep descriptions vivid but concise.`
        },
        {
          role: 'user' as const,
          content: this.buildPrompt(prompt, context)
        }
      ];

      const response = await fetch(this.baseUrl, {
        method: 'POST',
        headers: this.getHeaders(),
        body: JSON.stringify({
          model: this.model,
          messages,
          temperature: 0.8,
          max_tokens: 1000,
        }),
      });

      if (!response.ok) {
        throw new Error(`LM Studio API error: ${response.status} ${await response.text()}`);
      }

      const data = await response.json();
      return data.choices?.[0]?.message?.content || 'No response generated';
    } catch (error) {
      console.error('LLM generation failed:', error);
      throw error;
    }
  }

  async generateNPC(prompt: string, context: Record<string, unknown> = {}): Promise<GeneratedNPC> {
    try {
      const messages = [
        {
          role: 'system' as const,
          content: `You are a D&D NPC generator. Create interesting NPCs with names, descriptions, and roles.
                   Return JSON format: { name: string, description: string, role: "friendly" | "neutral" | "hostile" }`
        },
        {
          role: 'user' as const,
          content: `Generate an NPC based on this prompt: ${prompt}
                   Context: ${JSON.stringify(context)}
                   
                   Return ONLY valid JSON.`
        }
      ];

      const response = await fetch(this.baseUrl, {
        method: 'POST',
        headers: this.getHeaders(),
        body: JSON.stringify({
          model: this.model,
          messages,
          temperature: 0.7,
          max_tokens: 500,
        }),
      });

      if (!response.ok) {
        throw new Error(`LM Studio API error: ${response.status} ${await response.text()}`);
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content || '{}';
      
      // Try to parse JSON from response
      try {
        const jsonMatch = content.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          const parsed = JSON.parse(jsonMatch[0]) as GeneratedNPC;
          return {
            name: parsed.name || 'Unknown',
            description: parsed.description || '',
            role: parsed.role || 'neutral'
          };
        }
        return { name: 'Unknown', description: '', role: 'neutral' };
      } catch (e) {
        console.error('Failed to parse NPC JSON:', e);
        return { name: 'Unknown', description: '', role: 'neutral' };
      }
    } catch (error) {
      console.error('NPC generation failed:', error);
      throw error;
    }
  }

  async generateEvent(prompt: string, context: Record<string, unknown> = {}): Promise<GeneratedEvent> {
    try {
      const messages = [
        {
          role: 'system' as const,
          content: `You are a D&D event generator. Create exciting events and encounters for players.
                   Return JSON format: { title: string, description: string, difficulty: "easy" | "medium" | "hard" }`
        },
        {
          role: 'user' as const,
          content: `Generate an event based on this prompt: ${prompt}
                   Context: ${JSON.stringify(context)}
                   
                   Return ONLY valid JSON.`
        }
      ];

      const response = await fetch(this.baseUrl, {
        method: 'POST',
        headers: this.getHeaders(),
        body: JSON.stringify({
          model: this.model,
          messages,
          temperature: 0.8,
          max_tokens: 500,
        }),
      });

      if (!response.ok) {
        throw new Error(`LM Studio API error: ${response.status} ${await response.text()}`);
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content || '{}';
      
      try {
        const jsonMatch = content.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]) as GeneratedEvent;
        }
        return { title: 'Unknown Event', description: '', difficulty: 'medium' };
      } catch (e) {
        console.error('Failed to parse event JSON:', e);
        return { title: 'Unknown Event', description: '', difficulty: 'medium' };
      }
    } catch (error) {
      console.error('Event generation failed:', error);
      throw error;
    }
  }

  private buildPrompt(prompt: string, context: Record<string, unknown>): string {
    let fullPrompt = prompt;
    
    if (Object.keys(context).length > 0) {
      fullPrompt += `\n\nContext:\n`;
      fullPrompt += `- Current party: ${(context.party as string[])?.join(', ') || 'Unknown'}`;
      fullPrompt += `\n- Location: ${context.location || 'Unknown'}`;
      fullPrompt += `\n- Previous events: ${(context.previousEvents as string[])?.slice(-3).join('; ') || 'None'}`;
    }
    
    return fullPrompt;
  }

  async isConnected(): Promise<boolean> {
    // Test connection by making a simple request
    try {
      const response = await fetch(this.baseUrl, { 
        method: 'POST', 
        headers: this.getHeaders(),
        body: '{}' 
      });
      return response.ok || response.status === 400; // 400 means server is up but expecting proper format
    } catch {
      return false;
    }
  }

  async refreshModels(): Promise<string[]> {
    const models = await this.fetchModels();
    return models;
  }
}

export const llmClient = new LLMClient();
