// ============================================================================
// DnD Offline Multiplayer - LLM Client (OpenAI-compatible APIs)
// Supports: LM Studio, Ollama, OpenAI, Together AI, Groq, etc.
// ============================================================================

/**
 * Interface for NPC generated by AI
 */
interface GeneratedNPC {
  name: string;
  description?: string;
  role: 'friendly' | 'neutral' | 'hostile';
}

/**
 * Interface for Event generated by AI
 */
interface GeneratedEvent {
  title: string;
  description?: string;
  difficulty?: string;
}

/**
 * LLM Client - Universal API for OpenAI-compatible endpoints
 */
export class LLMClient {
  private baseUrl: string;
  private apiKey: string | null;
  private model: string;

  constructor() {
    // Read from environment variables (set at build time via Vite)
    const defaultUrl = import.meta.env.VITE_LLM_API_URL || 'http://localhost:1234/v1';
    const defaultKey = import.meta.env.VITE_LLM_API_KEY || '';
    
    // Try to load from localStorage first, fallback to env vars
    const storedUrl = localStorage.getItem('llmApiUrl');
    const storedKey = localStorage.getItem('llmApiKey');
    
    this.baseUrl = storedUrl || defaultUrl;
    this.apiKey = storedKey || (defaultKey ? defaultKey : null);
    this.model = localStorage.getItem('llmModel') || 'local-model';
  }

  setBaseUrl(url: string): void {
    // Ensure URL ends with /v1 if it doesn't have a specific endpoint
    let cleanUrl = url.replace(/\/(chat|models).*$/, '');
    if (!cleanUrl.endsWith('/v1')) {
      cleanUrl = `${cleanUrl}/v1`;
    }
    this.baseUrl = cleanUrl;
    localStorage.setItem('llmApiUrl', cleanUrl);
  }

  getBaseUrl(): string {
    return this.baseUrl;
  }

  setApiKey(key: string): void {
    this.apiKey = key || null;
    if (key) {
      localStorage.setItem('llmApiKey', key);
    } else {
      localStorage.removeItem('llmApiKey');
    }
  }

  getApiKey(): string | null {
    return this.apiKey;
  }

  setModel(model: string): void {
    this.model = model;
    localStorage.setItem('llmModel', model);
  }

  getModel(): string {
    return this.model;
  }

  private getHeaders(): Record<string, string> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    
    if (this.apiKey) {
      headers['Authorization'] = `Bearer ${this.apiKey}`;
    }
    
    return headers;
  }

  private getChatEndpoint(): string {
    return `${this.baseUrl}/chat/completions`;
  }

  private getModelsEndpoint(): string {
    return `${this.baseUrl}/models`;
  }

  private async fetchModels(): Promise<string[]> {
    try {
      const response = await fetch(this.getModelsEndpoint(), {
        method: 'GET',
        headers: this.getHeaders(),
      });

      if (response.ok) {
        const data = await response.json();
        console.log('LLM API models:', data);
        return data.data?.map((m: any) => m.id) || ['local-model'];
      } else {
        console.error('Failed to fetch models:', response.status, await response.text());
      }
    } catch (error) {
      console.error('Failed to fetch models:', error);
    }
    return ['local-model']; // Fallback
  }

  async generateScene(prompt: string, context: Record<string, unknown> = {}): Promise<string> {
    try {
      const messages = [
        {
          role: 'system' as const,
          content: `You are a D&D Dungeon Master assistant. Help create engaging scenes, NPCs, and events. 
                   Format your responses in markdown for better readability. Keep descriptions vivid but concise.`
        },
        {
          role: 'user' as const,
          content: this.buildPrompt(prompt, context)
        }
      ];

      const response = await fetch(this.getChatEndpoint(), {
        method: 'POST',
        headers: this.getHeaders(),
        body: JSON.stringify({
          model: this.model,
          messages,
          temperature: 0.8,
          max_tokens: 1000,
        }),
      });

      if (!response.ok) {
        throw new Error(`LLM API error: ${response.status} ${await response.text()}`);
      }

      const data = await response.json();
      return data.choices?.[0]?.message?.content || 'No response generated';
    } catch (error) {
      console.error('LLM generation failed:', error);
      throw error;
    }
  }

  async generateNPC(prompt: string, context: Record<string, unknown> = {}): Promise<GeneratedNPC> {
    try {
      const messages = [
        {
          role: 'system' as const,
          content: `You are a D&D NPC generator. Create interesting NPCs with names, descriptions, and roles.
                   Return JSON format: { name: string, description: string, role: "friendly" | "neutral" | "hostile" }`
        },
        {
          role: 'user' as const,
          content: `Generate an NPC based on this prompt: ${prompt}
                   Context: ${JSON.stringify(context)}
                   
                   Return ONLY valid JSON.`
        }
      ];

      const response = await fetch(this.getChatEndpoint(), {
        method: 'POST',
        headers: this.getHeaders(),
        body: JSON.stringify({
          model: this.model,
          messages,
          temperature: 0.7,
          max_tokens: 500,
        }),
      });

      if (!response.ok) {
        throw new Error(`LLM API error: ${response.status} ${await response.text()}`);
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content || '{}';
      
      // Try to parse JSON from response
      try {
        const jsonMatch = content.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          const parsed = JSON.parse(jsonMatch[0]) as GeneratedNPC;
          return {
            name: parsed.name || 'Unknown',
            description: parsed.description || '',
            role: parsed.role || 'neutral'
          };
        }
        return { name: 'Unknown', description: '', role: 'neutral' };
      } catch (e) {
        console.error('Failed to parse NPC JSON:', e);
        return { name: 'Unknown', description: '', role: 'neutral' };
      }
    } catch (error) {
      console.error('NPC generation failed:', error);
      throw error;
    }
  }

  async generateEvent(prompt: string, context: Record<string, unknown> = {}): Promise<GeneratedEvent> {
    try {
      const messages = [
        {
          role: 'system' as const,
          content: `You are a D&D event generator. Create exciting events and encounters for players.
                   Return JSON format: { title: string, description: string, difficulty: "easy" | "medium" | "hard" }`
        },
        {
          role: 'user' as const,
          content: `Generate an event based on this prompt: ${prompt}
                   Context: ${JSON.stringify(context)}
                   
                   Return ONLY valid JSON.`
        }
      ];

      const response = await fetch(this.getChatEndpoint(), {
        method: 'POST',
        headers: this.getHeaders(),
        body: JSON.stringify({
          model: this.model,
          messages,
          temperature: 0.8,
          max_tokens: 500,
        }),
      });

      if (!response.ok) {
        throw new Error(`LLM API error: ${response.status} ${await response.text()}`);
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content || '{}';
      
      try {
        const jsonMatch = content.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]) as GeneratedEvent;
        }
        return { title: 'Unknown Event', description: '', difficulty: 'medium' };
      } catch (e) {
        console.error('Failed to parse event JSON:', e);
        return { title: 'Unknown Event', description: '', difficulty: 'medium' };
      }
    } catch (error) {
      console.error('Event generation failed:', error);
      throw error;
    }
  }

  private buildPrompt(prompt: string, context: Record<string, unknown>): string {
    let fullPrompt = prompt;
    
    if (Object.keys(context).length > 0) {
      fullPrompt += `\n\nContext:\n`;
      fullPrompt += `- Current party: ${(context.party as string[])?.join(', ') || 'Unknown'}`;
      fullPrompt += `\n- Location: ${context.location || 'Unknown'}`;
      fullPrompt += `\n- Previous events: ${(context.previousEvents as string[])?.slice(-3).join('; ') || 'None'}`;
    }
    
    return fullPrompt;
  }

  async isConnected(): Promise<boolean> {
    // Test connection by checking the models endpoint first (lighter weight)
    try {
      const response = await fetch(this.getModelsEndpoint(), { 
        method: 'GET',
        headers: this.getHeaders(),
      });
      return response.ok || response.status === 401; // 401 means server is up but auth required
    } catch (error) {
      console.error('Connection test failed:', error);
      return false;
    }
  }

  async refreshModels(): Promise<string[]> {
    const models = await this.fetchModels();
    return models;
  }
}

export const llmClient = new LLMClient();
